version: '3.9'

services:
  microservice_first:
    build:
      context: /firstsrv
      dockerfile: Dockerfile
    container_name: microservice_first
    ports:
      - '8080:8080'
    environment:
      - KAFKA_BROKER=kafka_broker:9092
    depends_on:
      - kafka_broker

  microservice_second:
    build:
      context: /secsrv
      dockerfile: Dockerfile
    container_name: microservice_second
    ports:
      - '8081:8081'
    environment:
      - KAFKA_BROKER=kafka_broker:9092
    depends_on:
      - kafka_broker

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    ports:
      - "2181:2181"

  kafka_broker:
    image: confluentinc/cp-kafka:latest
    container_name: kafka_broker
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka_broker:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1